### ISSUE TITLE
Startup error when used with Skript 2.5.2

### ISSUE THREAD

**Issue by piotrskibapl** [TlatoaniHJ/WebSKT#3]
After updating Skript to the latest version (2.5.2), I get the following startup error of WebSKT:
```
[04:02:26] [Server thread/INFO]: [WebSKT] Enabling WebSKT v1.0-BETA.2*
[04:02:26] [Server thread/ERROR]: Error occurred while enabling WebSKT v1.0-BETA.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at us.tlatoani.webskt.core.registration_enum.ExprEnumValues.<clinit>(ExprEnumValues.java:20) ~[?:?]
	at us.tlatoani.webskt.core.registration_enum.EnumClassInfo.registerEnum(EnumClassInfo.java:29) ~[?:?]
	at us.tlatoani.webskt.WebSKT.loadSyntaxes(WebSKT.java:91) ~[?:?]
	at us.tlatoani.webskt.WebSKT.onEnable(WebSKT.java:61) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-312]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-312]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-312]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-312]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-312]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalStateException: Unable to find constructor for class ch.njol.skript.lang.ExpressionInfo ([class [Ljava.lang.String;, class java.lang.Class, class java.lang.Class, class java.lang.String]).
	at us.tlatoani.webskt.core.reflection.Reflection.getConstructor(Reflection.java:332) ~[?:?]
	at us.tlatoani.webskt.core.reflective_registration.ModifiableSyntaxElementInfo.<clinit>(ModifiableSyntaxElementInfo.java:25) ~[?:?]
	... 14 more
[04:02:26] [Server thread/INFO]: [WebSKT] Disabling WebSKT v1.0-BETA.2
[04:02:26] [Server thread/INFO]: [WebSKT] Stopped all WebSocket servers (if any were open)
```

Server version: git-Paper-312 (MC: 1.16.4)
WebSKT version: 1.0-BETA.2

**Comment by piotrskibapl** [comment]
It looks that it was a Skript issue and it is fixed now in Skript 2.5.3 version.
